
/* announcement actions */
export const LOAD_ANNOUNCEMENTS_SUCCESS = 'LOAD_ANNOUNCEMENTS_SUCCESS';
export const LOAD_ANNOUNCEMENT_SUCCESS = 'LOAD_ANNOUNCEMENT_SUCCESS';
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';
export const UPDATE_ANNOUNCEMENT_SUCCESS = 'UPDATE_ANNOUNCEMENT_SUCCESS';

/* ajax calls */
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

/* offer actions */
export const LOAD_CAR_MARKS_SUCCESS = 'LOAD_CAR_MARKS_SUCCESS';
export const LOAD_CAR_MODELES_SUCCESS = 'LOAD_CAR_MODELES_SUCCESS';
