export default [
    { "id": "1", "mark": "Audi", "shortName": "audi","models":["100","200","80","A","A1","A2","A3","A4","A4 ALLROAD","A5","A6","A6 ALLROAD","A7","A8","ALLROAD","COUPE","COUPE GT","Q2","Q3","Q5","Q7","Q8","QUATTRO","R8","RS Q3","RS2","RS3","RS4","RS5","RS6","RS7","S1","S3","S4","S5","S6","S7","S8","SQ5","SQ7","TT","TT RS","TTS"]},
    { "id": "2", "mark": "Bmw", "shortName": "bmw","models":["2000", "2002", "2800", "3.0", "600", "ALPINA", "I3", "I8", "SERIE 1", "SERIE 2", "SERIE 3", "SERIE 3 GT", "SERIE 4", "SERIE 5", "SERIE 5 GT", "SERIE 6", "SERIE 7", "SERIE 8", "X1", "X2", "X3", "X4", "X5", "X6", "Z1", "Z3", "Z4", "Z8"]},
    { "id": "3", "mark": "Citroen", "shortName": "citroen", "models":["2CV", "ACADIANE", "AMI", "AX", "B2", "BERLINGO", "BX", "C-CROSSER", "C-ELYSEE", "C-ZERO", "C1", "C15", "C2", "C25", "C3", "C3 AIRCROSS", "C3 PICASSO", "C3 PLURIEL", "C35", "C4", "C4 AIRCROSS", "C4 CACTUS", "C4 PICASSO", "C4 SPACETOURER", "C5", "C5 AIRCROSS", "C6", "C8", "CX", "DS", "DS3", "DS4", "DS5", "DYANE", "E-MEHARI", "EVASION", "GRAND C4 PICASSO", "GRAND C4 SPACETOURER", "GSA", "ID", "JUMPER", "JUMPY", "MEHARI", "NEMO", "PICASSO", "SAXO", "SM", "SPACETOURER", "TRACTION", "VISA", "XANTIA", "XM", "XSARA", "ZX"]},
    { "id": "4", "mark": "Ford", "shortName": "ford","models":[]},
    { "id": "5", "mark": "Fiat", "shortName": "fiat","models":[]},
    { "id": "7", "mark": "Mercedes", "shortName": "mercedes","models":[]},
    { "id": "8", "mark": "Opel", "shortName": "opel","models":[]},
    { "id": "9", "mark": "Peugeot", "shortName": "peugeot","models":[]},
    { "id": "10", "mark": "Renault", "shortName": "renault","models":[]},
    { "id": "11", "mark": "Volkswagen", "shortName": "volkswagen","models":[]},
    { "id": "12", "mark": "Abarth", "shortName": "abarth","models":[]},
    { "id": "13", "mark": "Aleko","models":[]},
    { "id": "14", "mark": "Alfa Romeo", "shortName": "alfa-romeo","models":[]},
    { "id": "15", "mark": "Alpina", "shortName": "alpina","models":[]},
    { "id": "16", "mark": "Aro", "shortName": "aro","models":[]},
    { "id": "17", "mark": "Artega", "shortName": "artega","models":[]},
    { "id": "18", "mark": "Aston Martin", "shortName": "aston-martin","models":[]},
    { "id": "19", "mark": "Autobianchi", "shortName": "autobianchi","models":[]},
    { "id": "20", "mark": "Auverland", "shortName": "auverland","models":[]},
    { "id": "21", "mark": "Bentley", "shortName": "bentley","models":[]},
    { "id": "22", "mark": "Bertone", "shortName": "bertone","models":[]},
    { "id": "23", "mark": "Bluecar Groupe Bollore","models":[]},
    { "id": "24", "mark": "Buick", "shortName": "buick","models":[]},
    { "id": "25", "mark": "Cadillac", "shortName": "cadillac","models":[]},
    { "id": "26", "mark": "Chevrolet", "shortName": "chevrolet","models":[]},
    { "id": "27", "mark": "Chrysler", "shortName": "chrysler","models":[]},
    { "id": "28", "mark": "Corvette", "shortName": "corvette","models":[]},
    { "id": "29", "mark": "Dacia", "shortName": "dacia","models":[]},
    { "id": "30", "mark": "Daewoo", "shortName": "daewoo","models":[]},
    { "id": "31", "mark": "Daihatsu", "shortName": "daihatsu","models":[]},
    { "id": "32", "mark": "Dangel", "shortName": "dangel","models":[]},
    { "id": "33", "mark": "De La Chapelle", "shortName": "de-la-chapelle","models":[]},
    { "id": "34", "mark": "Dodge", "shortName": "dodge","models":[]},
    { "id": "35", "mark": "Donkervoort", "shortName": "donkervoort","models":[]},
    { "id": "36", "mark": "Dr", "shortName": "dr-motor","models":[]}, 
    { "id": "37", "mark": "Ds", "shortName": "ds","models":[]}, 
    { "id": "38", "mark": "Ferrari", "shortName": "ferrari","models":[]}, 
    { "id": "39", "mark": "Fisker", "shortName": "fisker","models":[]},
    { "id": "40", "mark": "Gme","models":[]},
    { "id": "41", "mark": "Honda", "shortName": "honda","models":[]},
    { "id": "42", "mark": "Hummer", "shortName": "hummer","models":[]},
    { "id": "43", "mark": "Hyundai", "shortName": "hyundai","models":[]},
    { "id": "44", "mark": "Infiniti", "shortName": "infiniti","models":[]},
    { "id": "45", "mark": "Innocenti"},
    { "id": "46", "mark": "Isuzu", "shortName": "isuzu","models":[]},
    { "id": "47", "mark": "Iveco", "shortName": "iveco","models":[]},
    { "id": "48", "mark": "Jaguar", "shortName": "jaguar","models":[]},
    { "id": "49", "mark": "Jeep", "shortName": "jeep","models":[]},
    { "id": "50", "mark": "Kia", "shortName": "kia","models":[]},
    { "id": "51", "mark": "Lada", "shortName": "lada","models":[]},
    { "id": "52", "mark": "Lamborghini", "shortName": "lamborghini","models":[]},
    { "id": "53", "mark": "Lancia", "shortName": "lancia","models":[]},
    { "id": "54", "mark": "Land Rover", "shortName": "land-rover","models":[]},
    { "id": "55", "mark": "Lexus", "shortName": "lexus","models":[]},
    { "id": "56", "mark": "Lotus", "shortName": "lotus","models":[]},
    { "id": "57", "mark": "Mahindra", "shortName": "mahindra","models":[]},
    { "id": "58", "mark": "Maruti", "shortName": "maruti","models":[]},
    { "id": "59", "mark": "Maserati", "shortName": "maserati","models":[]},
    { "id": "60", "mark": "Mastretta","models":[]},
    { "id": "61", "mark": "Maybach", "shortName": "maybach","models":[]},
    { "id": "62", "mark": "Mazda", "shortName": "mazda","models":[]},
    { "id": "63", "mark": "Mclaren", "shortName": "mclaren","models":[]},
    { "id": "64", "mark": "Mega", "shortName": "mega","models":[]},
    { "id": "65", "mark": "Mg", "shortName": "mg","models":[]},
    { "id": "66", "mark": "Mia", "shortName": "mia-electric","models":[]},
    { "id": "67", "mark": "Mini", "shortName": "mini","models":[]},
    { "id": "68", "mark": "Mitsubishi", "shortName": "mitsubishi","models":[]},
    { "id": "69", "mark": "Morgan", "shortName": "morgan","models":[]},
    { "id": "70", "mark": "Nissan", "shortName": "nissan","models":[]},
    { "id": "71", "mark": "Pgo", "shortName": "pgo","models":[]},
    { "id": "72", "mark": "Piaggio", "shortName": "piaggio","models":[]},
    { "id": "73", "mark": "Polski/fso", "shortName": "polski","models":[]},
    { "id": "74", "mark": "Pontiac", "shortName": "pontiac","models":[]},
    { "id": "75", "mark": "Porsche", "shortName": "porsche","models":[]},
    { "id": "76", "mark": "Proton", "shortName": "proton","models":[]},
    { "id": "77", "mark": "Rolls-royce", "shortName": "rolls-royce","models":[]},
    { "id": "78", "mark": "Rover", "shortName": "rover","models":[]},
    { "id": "79", "mark": "Saab", "shortName": "saab","models":[]},
    { "id": "80", "mark": "Santana", "shortName": "santana","models":[]},
    { "id": "81", "mark": "Seat", "shortName": "seat","models":[]},
    { "id": "82", "mark": "Shuanghuan", "shortName": "shuanghuan","models":[]},
    { "id": "83", "mark": "Skoda", "shortName": "skoda","models":[]},
    { "id": "84", "mark": "Smart", "shortName": "smart","models":[]},
    { "id": "85", "mark": "Ssangyong", "shortName": "ssangyong","models":[]},
    { "id": "86", "mark": "Subaru", "shortName": "subaru","models":[]},
    { "id": "87", "mark": "Suzuki", "shortName": "suzuki","models":[]},
    { "id": "88", "mark": "Talbot", "shortName": "talbot-simca","models":[]},
    { "id": "89", "mark": "Tavria","models":[]},
    { "id": "90", "mark": "Tesla", "shortName": "tesla","models":[]},
    { "id": "91", "mark": "Toyota", "shortName": "toyota","models":[]},
    { "id": "92", "mark": "Tvr", "shortName": "tvr","models":[]},
    { "id": "93", "mark": "Venturi", "shortName": "venturi","models":[]},
    { "id": "94", "mark": "Volvo", "shortName": "volvo","models":[]},
    { "id": "95", "mark": "Autres" }
]