export default[
    { "id": "1", "label": "Job offers" },
    { "id": "2", "label": "Cars" },
    { "id": "3", "label": "Motorcycles" },
    { "id": "4", "label": "Caravanning" },
    { "id": "5", "label": "Utilities" },
    { "id": "6", "label": "Auto Equipment" },
    { "id": "7", "label": "Moto equipment" },
    { "id": "8", "label": "Caravanning Equipment" },
    { "id": "9", "label": "Boating" },
    { "id": "10", "label": "Equipment Nautisme" },
    { "id": "11", "label": "Sales" },
    { "id": "12", "label": "Rentals" },
    { "id": "13", "label": "Roommates" },
    { "id": "14", "label": "Commercial Offices" },
    { "id": "15", "label": "Holiday Rentals" },
    { "id": "16", "label": "Bed and Breakfast" },
    { "id": "17", "label": "Campsites" },
    { "id": "18", "label": "Hotels" },
    { "id": "19", "label": "Unusual accommodations" },
    { "id": "20", "label": "Computer science" },
    { "id": "21", "label": "Consoles & Video Games" },
    { "id": "22", "label": "Image & Sound" },
    { "id": "23", "label": "Telephony" },
    { "id": "24", "label": "Furnishing" },
    { "id": "25", "label": "Appliances" },
    { "id": "26", "label": "Tableware" },
    { "id": "27", "label": "Decoration" },
    { "id": "28", "label": "Linen" },
    { "id": "29", "label": "DIY" },
    { "id": "30", "label": "Gardening" },
    { "id": "31", "label": "Clothing" },
    { "id": "32", "label": "Shoes" },
    { "id": "33", "label": "Accessories & Luggage" },
    { "id": "34", "label": "Watches & Jewelry" },
    { "id": "35", "label": "baby equipment" },
    { "id": "36", "label": "Baby clothes" },
    { "id": "37", "label": "DVD / Movies" },
    { "id": "38", "label": "CD / Music" },
    { "id": "39", "label": "Books" },
    { "id": "40", "label": "Animals" },
    { "id": "41", "label": "Bicycles" },
    { "id": "42", "label": "Sports" },
    { "id": "43", "label": "musical instruments" },
    { "id": "44", "label": "Collection" },
    { "id": "45", "label": "Toys Games" },
    { "id": "46", "label": "Gastronomy Wines" },
    { "id": "47", "label": "Agricultural Equipment" },
    { "id": "48", "label": "Transport - Handling" },
    { "id": "49", "label": "Construction - Construction site" },
    { "id": "50", "label": "Tools - Materials 2nd-work" },
    { "id": "51", "label": "Industrial Equipment" },
    { "id": "52", "label": "Catering - Hotels" },
    { "id": "53", "label": "Office Supplies" },
    { "id": "54", "label": "Shops & Markets" },
    { "id": "55", "label": "Medical Equipment" },
    { "id": "56", "label": "Services" },
    { "id": "57", "label": "Ticket" },
    { "id": "58", "label": "Events" },
    { "id": "59", "label": "Private lessons" },
    { "id": "60", "label": "Carpool" },
    { "id": "61", "label": "Other" },
    { "id": "1", "label": "Offres d'emploi" },
    { "id": "2", "label": "Voitures" },
    { "id": "3", "label": "motos" },
    { "id": "4", "label": "Caravaning" },
    { "id": "5", "label": "Utilitaires" },
    { "id": "6", "label": "Auto Equipment" },
    { "id": "7", "label": "Equipement moto" },
    { "id": "8", "label": "Equipement de caravaning" },
    { "id": "9", "label": "Navigation de plaisance" },
    { "id": "10", "label": "Equipement Nautisme" },
    { "id": "11", "label": "Ventes" },
    { "id": "12", "label": "Location" },
    { "id": "13", "label": "Colocataires" },
    { "id": "14", "label": "Bureaux commerciaux" },
    { "id": "15", "label": "Locations de vacances" },
    { "id": "16", "label": "Chambres d'hôtes" },
    { "id": "17", "label": "Campings" },
    { "id": "18", "label": "Hôtels" },
    { "id": "19", "label": "Hébergements insolites" },
    { "id": "20", "label": "Informatique" },
    { "id": "21", "label": "Consoles et jeux vidéos" },
    { "id": "22", "label": "Image et son" },
    { "id": "23", "label": "Téléphonie" },
    { "id": "24", "label": "Ameublement" },
    { "id": "25", "label": "Appareils" },
    { "id": "26", "label": "Vaisselle" },
    { "id": "27", "label": "Décoration" },
    { "id": "28", "label": "Lin" },
    { "id": "29", "label": "bricolage" },
    { "id": "30", "label": "Jardinage" },
    { "id": "31", "label": "Vêtements" },
    { "id": "32", "label": "Chaussures" },
    { "id": "33", "label": "Accessoires et bagages" },
    { "id": "34", "label": "Montres & Bijoux" },
    { "id": "35", "label": "équipement bébé" },
    { "id": "36", "label": "Vêtements pour bébé" },
    { "id": "37", "label": "DVD / Films" },
    { "id": "38", "label": "CD / Musique" },
    { "id": "39", "label": "Livres" },
    { "id": "40", "label": "Animaux" },
    { "id": "41", "label": "Vélos" },
    { "id": "42", "label": "Sports" },
    { "id": "43", "label": "instruments de musique" },
    { "id": "44", "label": "Collection" },
    { "id": "45", "label": "Jeux de jouets" },
    { "id": "46", "label": "Vins de gastronomie" },
    { "id": "47", "label": "Matériel agricole" },
    { "id": "48", "label": "Transport - Manutention" },
    { "id": "49", "label": "Construction - chantier" },
    { "id": "50", "label": "Outils - Matériaux 2e oeuvre" },
    { "id": "51", "label": "Equipement industriel" },
    { "id": "52", "label": "Restauration - Hôtels" },
    { "id": "53", "label": "Fournitures de bureau" },
    { "id": "54", "label": "Boutiques et marchés" },
    { "id": "55", "label": "équipement médical" },
    { "id": "56", "label": "Services" },
    { "id": "57", "label": "Ticket" },
    { "id": "58", "label": "Événements" },
    { "id": "59", "label": "Cours particuliers" },
    { "id": "60", "label": "Covoiturage" },
    { "id": "61", "label": "Autre" }
]