export default {
  "id": "",
  "category": 0,
  "type": 0,
  "title": "",
  "description": "",
  "shortDescription":"shortDescription",
  "mainPicture": "http://placehold.it/708x472",
  "pictures": [
    "https://via.placeholder.com/500x350",
    "https://via.placeholder.com/500x350",
    "https://via.placeholder.com/500x350",
    "https://via.placeholder.com/500x350"
  ],
  "shortDescription": "",
  "normalPrix": "",
  "amount": "",
  "createAt": "",
  "lastModifDate": "",
  "viewCount": 0,
  "likeCount": 0,
  "currency": "",
  "location": {
    "city": "",
    "country": "",
    "address":"",
    "zipCode":"",
    "numberOfStreet":"",
    "placeKnownAs":"",
    "streetName":""
  },
  "criteria": {
    "mark": "",
    "cylinder": "",
    "mileage": "",
    "model": "",
    "yearOfModel": "",
    "typeOfFuel": "",
    "typeOfGearBox": "",
    "sizeOfSurface": "",
    "immovableType": "",
    "isEquiped": false,
    "numberOfRooms": "",
    "energyClassification": "",
    "ges": "",
    "numberOfPeople": "",
    "numberOfVacationRooms": "",
    "hasSwimingPool": false
  },
  "owner": {
    "id": "",
    "profile": 'http://placehold.it/50x50',
    "typeOfProfile": 0,
    "name": "",
    "gender": "",
    "company": "",
    "email": "",
    "phone": "",
    "hidePhone": true,
    "address": "",
    "about": "",
    "toBeContacted": false,
    "toBeContactedForMarketing": false,
    "isConneted": false,
    "likeCount": 0,
    "greeting": "",
  }
}