export default function () {
    return [
        { checked: false, disabled: false, icon: null, value: "Audi" },
        { checked: false, disabled: false, icon: null, value: "Bmw" },
        { checked: false, disabled: false, icon: null, value: "Citroen" },
        { checked: false, disabled: false, icon: null, value: "Ford" },
        { checked: false, disabled: false, icon: null, value: "Fiat" },
        { checked: false, disabled: false, icon: null, value: "Mercedes" },
        { checked: false, disabled: false, icon: null, value: "Opel" },
        { checked: false, disabled: false, icon: null, value: "Peugeot" },
        { checked: false, disabled: false, icon: null, value: "Renault" },
        { checked: false, disabled: false, icon: null, value: "Volkswagen" },
        { checked: false, disabled: false, icon: null, value: "Abarth" },
        { checked: false, disabled: false, icon: null, value: "Aleko" },
        { checked: false, disabled: false, icon: null, value: "Alfa Romeo" },
        { checked: false, disabled: false, icon: null, value: "Alpina" },
        { checked: false, disabled: false, icon: null, value: "Aro" },
        { checked: false, disabled: false, icon: null, value: "Artega" },
        { checked: false, disabled: false, icon: null, value: "Aston Martin" },
        { checked: false, disabled: false, icon: null, value: "Autobianchi" },
        { checked: false, disabled: false, icon: null, value: "Auverland" },
        { checked: false, disabled: false, icon: null, value: "Bentley" },
        { checked: false, disabled: false, icon: null, value: "Bertone" },
        { checked: false, disabled: false, icon: null, value: "Bluecar Groupe Bollore" },
        { checked: false, disabled: false, icon: null, value: "Buick" },
        { checked: false, disabled: false, icon: null, value: "Cadillac" },
        { checked: false, disabled: false, icon: null, value: "Chevrolet" },
        { checked: false, disabled: false, icon: null, value: "Chrysler" },
        { checked: false, disabled: false, icon: null, value: "Corvette" },
        { checked: false, disabled: false, icon: null, value: "Dacia" },
        { checked: false, disabled: false, icon: null, value: "Daewoo" },
        { checked: false, disabled: false, icon: null, value: "Daihatsu" },
        { checked: false, disabled: false, icon: null, value: "Dangel" },
        { checked: false, disabled: false, icon: null, value: "De La Chapelle" },
        { checked: false, disabled: false, icon: null, value: "Dodge" },
        { checked: false, disabled: false, icon: null, value: "Donkervoort" },
        { checked: false, disabled: false, icon: null, value: "Dr" },
        { checked: false, disabled: false, icon: null, value: "Ds" },
        { checked: false, disabled: false, icon: null, value: "Ferrari" },
        { checked: false, disabled: false, icon: null, value: "Fisker" },
        { checked: false, disabled: false, icon: null, value: "Gme" },
        { checked: false, disabled: false, icon: null, value: "Honda" },
        { checked: false, disabled: false, icon: null, value: "Hummer" },
        { checked: false, disabled: false, icon: null, value: "Hyundai" },
        { checked: false, disabled: false, icon: null, value: "Infiniti" },
        { checked: false, disabled: false, icon: null, value: "Innocenti" },
        { checked: false, disabled: false, icon: null, value: "Isuzu" },
        { checked: false, disabled: false, icon: null, value: "Iveco" },
        { checked: false, disabled: false, icon: null, value: "Jaguar" },
        { checked: false, disabled: false, icon: null, value: "Jeep" },
        { checked: false, disabled: false, icon: null, value: "Kia" },
        { checked: false, disabled: false, icon: null, value: "Lada" },
        { checked: false, disabled: false, icon: null, value: "Lamborghini" },
        { checked: false, disabled: false, icon: null, value: "Lancia" },
        { checked: false, disabled: false, icon: null, value: "Land Rover" },
        { checked: false, disabled: false, icon: null, value: "Lexus" },
        { checked: false, disabled: false, icon: null, value: "Lotus" },
        { checked: false, disabled: false, icon: null, value: "Mahindra" },
        { checked: false, disabled: false, icon: null, value: "Maruti" },
        { checked: false, disabled: false, icon: null, value: "Maserati" },
        { checked: false, disabled: false, icon: null, value: "Mastretta" },
        { checked: false, disabled: false, icon: null, value: "Maybach" },
        { checked: false, disabled: false, icon: null, value: "Mazda" },
        { checked: false, disabled: false, icon: null, value: "Mclaren" },
        { checked: false, disabled: false, icon: null, value: "Mega" },
        { checked: false, disabled: false, icon: null, value: "Mg" },
        { checked: false, disabled: false, icon: null, value: "Mia" },
        { checked: false, disabled: false, icon: null, value: "Mini" },
        { checked: false, disabled: false, icon: null, value: "Mitsubishi" },
        { checked: false, disabled: false, icon: null, value: "Morgan" },
        { checked: false, disabled: false, icon: null, value: "Nissan" },
        { checked: false, disabled: false, icon: null, value: "Pgo" },
        { checked: false, disabled: false, icon: null, value: "Piaggio" },
        { checked: false, disabled: false, icon: null, value: "Polski/fso" },
        { checked: false, disabled: false, icon: null, value: "Pontiac" },
        { checked: false, disabled: false, icon: null, value: "Porsche" },
        { checked: false, disabled: false, icon: null, value: "Proton" },
        { checked: false, disabled: false, icon: null, value: "Rolls-royce" },
        { checked: false, disabled: false, icon: null, value: "Rover" },
        { checked: false, disabled: false, icon: null, value: "Saab" },
        { checked: false, disabled: false, icon: null, value: "Santana" },
        { checked: false, disabled: false, icon: null, value: "Seat" },
        { checked: false, disabled: false, icon: null, value: "Shuanghuan" },
        { checked: false, disabled: false, icon: null, value: "Skoda" },
        { checked: false, disabled: false, icon: null, value: "Smart" },
        { checked: false, disabled: false, icon: null, value: "Ssangyong" },
        { checked: false, disabled: false, icon: null, value: "Subaru" },
        { checked: false, disabled: false, icon: null, value: "Suzuki" },
        { checked: false, disabled: false, icon: null, value: "Talbot" },
        { checked: false, disabled: false, icon: null, value: "Tavria" },
        { checked: false, disabled: false, icon: null, value: "Tesla" },
        { checked: false, disabled: false, icon: null, value: "Toyota" },
        { checked: false, disabled: false, icon: null, value: "Tvr" },
        { checked: false, disabled: false, icon: null, value: "Venturi" },
        { checked: false, disabled: false, icon: null, value: "Volvo" },
        { checked: false, disabled: false, icon: null, value: "Autres" }
    ];
};
