export default function (t) {
    return [
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.job.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.1') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.vehicule.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '2') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '3') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '4') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '5') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '6') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '7') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '8') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '9') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '10') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.immovable.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '11') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '12') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '13') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '14') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.vacation.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '15') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '16') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '17') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '18') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '19') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.multimedia.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '20') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '21') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '22') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '23') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.house.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '24') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '25') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '26') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '27') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '28') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '29') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '30') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '31') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '32') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '33') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '34') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '35') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '36') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.hobbies.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '37') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '38') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '39') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '40') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '41') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '42') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '43') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '44') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '45') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '46') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.equipments.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '47') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '48') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '49') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '50') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '51') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '52') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '53') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '54') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '55') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.services.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '56') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '57') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '58') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '59') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '60') },
        { checked: false, disabled: true, icon: null, value: t('edit.form.category.categories.others.title') },
        { checked: false, disabled: false, icon: null, value: t('edit.form.categories.' + '61') },
    ];
};
